version: "3.8"

services:
  web:
    build: .
    container_name: medicar_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  
  db:
    image: postgres:13
    container_name: medicar_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=MedicarDB
      - POSTGRES_PORT=5432
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  agent:
    image: portainer/agent
    container_name: medicar_agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes

  portainer:
    image: portainer/portainer-ce
    container_name: medicar_portrainer
    command: -H tcp://agent:9001 --tlsskipverify
    ports:
      - "9000:9000"
    volumes:
      - portainer_data:/data

volumes:
  postgres_data:
  portainer_data: